#!/usr/bin/env python

from __future__ import annotations

import sys as _sys
from pathlib import Path as _Path

_PROJECT_ROOT = _Path(__file__).resolve().parent.parent
if str(_PROJECT_ROOT) not in _sys.path:
    _sys.path.insert(0, str(_PROJECT_ROOT))

import json
from pathlib import Path

from src.evaluation.error_analysis import categorize_examples, summarize_retrieval_quality
from src.evaluation.significance import compare_predictions
from src.utils.logger import get_logger

logger = get_logger(__name__)

LOGS_DIR = Path("experiments/logs")
REPORT_PATH = Path("docs/experiments_findings.md")


def _read_jsonl(path: Path) -> list[dict]:
    with open(path, "r", encoding="utf-8") as f:
        return [json.loads(line) for line in f if line.strip()]


def _read_json(path: Path) -> dict:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def generate_report() -> None:
    baseline_predictions_path = LOGS_DIR / "baseline_predictions.jsonl"
    rag_predictions_path = LOGS_DIR / "rag_predictions.jsonl"
    baseline_metrics_path = LOGS_DIR / "baseline_metrics.json"
    rag_metrics_path = LOGS_DIR / "rag_metrics.json"
    sweep_path = LOGS_DIR / "topk_sweep.json"

    missing = [
        p
        for p in (baseline_predictions_path, rag_predictions_path)
        if not p.is_file()
    ]
    if missing:
        missing_str = ", ".join(str(p) for p in missing)
        raise FileNotFoundError(
            f"Missing required prediction file(s): {missing_str}. "
            "Run scripts/run_baseline.py and scripts/run_rag_eval.py first."
        )

    baseline_records = _read_jsonl(baseline_predictions_path)
    rag_records = _read_jsonl(rag_predictions_path)

    baseline_metrics = (
        _read_json(baseline_metrics_path) if baseline_metrics_path.is_file() else None
    )
    rag_metrics = _read_json(rag_metrics_path) if rag_metrics_path.is_file() else None

    significance_results = compare_predictions(baseline_records, rag_records)
    categorized, category_summary = categorize_examples(baseline_records, rag_records)
    retrieval_quality = summarize_retrieval_quality(rag_records)
    sweep_results = _read_json(sweep_path) if sweep_path.is_file() else None

    lines = _build_report_lines(
        baseline_metrics,
        rag_metrics,
        significance_results,
        category_summary,
        retrieval_quality,
        sweep_results,
    )
    REPORT_PATH.write_text("\n".join(lines), encoding="utf-8")
    logger.info("Wrote %s", REPORT_PATH)


def _build_report_lines(
    baseline_metrics: dict | None,
    rag_metrics: dict | None,
    significance_results: dict,
    category_summary: dict,
    retrieval_quality: dict,
    sweep_results: dict | None,
) -> list[str]:
    lines = [
    "# Experiment Findings",
    "",
    "> Generated by `scripts/generate_report.py`. Re-run after new experiments.",
    "",
    "## Headline Metrics",
    "",
    ]

    if baseline_metrics and rag_metrics:
        lines += [
            "| Metric | Baseline | RAG | Delta |",
            "|---|---|---|---|",
        ]
        for key in ("closed_accuracy", "open_bleu", "open_rouge_l", "overall_exact_match"):
            b = baseline_metrics.get(key)
            r = rag_metrics.get(key)
            if b is None or r is None:
                continue
            lines.append(f"| {key} | {b:.4f} | {r:.4f} | {r - b:+.4f} |")
        lines.append("")
    else:
        lines += [
            "_Baseline and/or RAG metrics summary not found — run both eval scripts first._",
            "",
        ]

    lines += ["## Statistical Significance (paired bootstrap, 95% CI)", ""]
    if significance_results:
        lines += [
            "| Comparison | Observed Delta | 95% CI | p-value | Significant (p<0.05)? |",
            "|---|---|---|---|---|",
        ]
        for name, result in significance_results.items():
            ci = f"[{result['ci_lower']:.4f}, {result['ci_upper']:.4f}]"
            sig = "Yes" if result["significant_at_0_05"] else "No"
            lines.append(
                f"| {name} | {result['observed_delta']:+.4f} | {ci} | "
                f"{result['p_value']:.4f} | {sig} |"
            )
        lines.append("")
        lines.append(
            "_Interpretation: a p-value below 0.05 means the sign of the "
            "observed delta was stable across 95%+ of bootstrap resamples — "
            "i.e. unlikely to be an artifact of which examples happen to be "
            "in the test split. It does not by itself establish practical "
            "significance; consider the effect size (Observed Delta) too._"
        )
        lines.append("")
    else:
        lines += ["_No shared examples found between baseline and RAG predictions._", ""]

    lines += [
        "## Error Analysis: Where Does Retrieval Help or Hurt?",
        "",
        "| Category | Count | Meaning |",
        "|---|---|---|",
        f"| Improved | {category_summary['counts']['improved']} | RAG correct, baseline wrong |",
        f"| Regressed | {category_summary['counts']['regressed']} | Baseline correct, RAG wrong |",
        f"| Both correct | {category_summary['counts']['both_correct']} | No change, both right |",
        f"| Both wrong | {category_summary['counts']['both_wrong']} | No change, both wrong |",
        "",
        "Example IDs for manual review (capped per category; full predictions "
        "with retrieved evidence are in `experiments/logs/rag_predictions.jsonl`):",
        "",
    ]
    for category, ids in category_summary["example_ids"].items():
        if ids:
            lines.append(f"- **{category}**: {', '.join(ids)}")
    lines.append("")

    if retrieval_quality["mean_top1_similarity"] is not None:
        top1_line = (
            f"- Mean top-1 similarity score: {retrieval_quality['mean_top1_similarity']:.4f}"
        )
    else:
        top1_line = "- Mean top-1 similarity score: N/A (no evidence retrieved for any example)"

    lines += [
        "## Retrieval Quality",
        "",
        f"- Examples evaluated: {retrieval_quality['n_examples']}",
        top1_line,
        f"- Mean number of items retrieved per query: "
        f"{retrieval_quality['mean_num_retrieved']:.2f}",
        f"- Examples with zero retrieved evidence: "
        f"{retrieval_quality['pct_examples_with_no_evidence']:.1%} "
        "(these fall back to baseline-equivalent behavior)",
        "",
    ]

    lines += ["## top_k Sweep", ""]
    if sweep_results:
        lines += [
            "| top_k | closed_accuracy | open_bleu | open_rouge_l |",
            "|---|---|---|---|",
        ]
        for k in sorted(sweep_results, key=lambda x: int(x)):
            m = sweep_results[k]
            lines.append(
                f"| {k} | {m['closed_accuracy']:.4f} | {m['open_bleu']:.4f} | "
                f"{m['open_rouge_l']:.4f} |"
            )
        lines.append("")
    else:
        lines += [
            "_No sweep results found — run `python scripts/run_experiments.py` "
            "to test how accuracy varies with the number of retrieved items._",
            "",
        ]

    return lines


if __name__ == "__main__":
    generate_report()
